---
# Homepage configuration
# See https://fontawesome.com/search for icons options

title: "Personal Dashboard"
subtitle: "A simple Homepage for all services"
# logo: "logo.png"
icon: "fas fa-skull-crossbones" # Optional icon

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Home"
    icon: "fas fa-book"
    url: "https://mix.youya.org/mixhub/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page"

# Optional message
# message:
#   #url: https://b4bz.io
#   style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#   title: "Notice"
#   icon: "fa fa-grin"
#   content: "Homelab services are only accessible from LAN."

header: true
footer: false
# footer: '<p>Powered by Homer</p>' # set false if you want to hide it.

# Optional theme customization
theme: default # themes available in 'src/assets/themes'

# Optional theme customization (color overrrides)
# overrrides can also be done using CSS vars
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Set the default layout and color scheme
defaults:
  layout: list # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Online Services"
    icon: "fas fa-cloud"
    items:
      - name: "Markdown Editor"
        icon: "fa-solid fa-pen-to-square"
        subtitle: "Powerfull Markdown Editor"
        tag: "tool"
        url: "https://mix.youya.org/md2pdf/"
      - name: "Clash Meta"
        icon: "fa-solid fa-shield-cat"
        subtitle: "Clash Meta Dashboard"
        tag: "tool"
        url: "https://mix.youya.org/clash-yacd/"
      - name: "Dashboard icons"
        icon: "fa-solid fa-icons"
        subtitle: "Dashboard icons"
        tag: "setup"
        url: "https://mix.youya.org/mixhub/"
  - name: "Homelab Services"
    icon: "fas fa-house-lock"
    items:
      - name: "AdGuard Home"
        icon: "fa-solid fa-shield-halved"
        subtitle: "Blocks ads & protects privacy"
        tag: "tool"
        url: "http://lab.youya.org:3000"
      - name: "Alist"
        icon: "fa-solid fa-hard-drive"
        subtitle: "Centralized drives"
        tag: "tool"
        url: "https://lab.youya.org:5443/alist"
      - name: "Mi Music"
        icon: "fa-solid fa-music"
        subtitle: "Music for Xiaomi Sound Box"
        tag: "music"
        url: "http://lab.youya.org:8090"
      - name: "Jellyfin"
        icon: "fa-solid fa-video"
        subtitle: "Self hosted Media Center"
        tag: "video"
        url: "http://lab.youya.org:8096"
      - name: "Immich Photos"
        icon: "fa-solid fa-image"
        subtitle: "High performance photo and video solution"
        tag: "photo"
        url: "http://lab.youya.org:2283"
      - name: "Aria2"
        icon: "fa-solid fa-cloud-arrow-down"
        subtitle: "Aria2 Web UI"
        tag: "tool"
        url: "https://mix.youya.org/aria2/#!/settings/rpc/set/https/lab.youya.org/5443/aria2-jsonrpc/YXJpYTJj"
